// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UkwWypozyczalnia.DAL;

#nullable disable

namespace UkwWypozyczalnia.Migrations
{
    [DbContext(typeof(FilmsContext))]
    [Migration("20230612200732_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UkwWypozyczalnia.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Komedia"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Familijne"
                        });
                });

            modelBuilder.Entity("UkwWypozyczalnia.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Director = "Person A",
                            Price = 17.49f,
                            Title = "Film A"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Director = "Person B",
                            Price = 24.89f,
                            Title = "Film B"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Director = "Person C",
                            Price = 31.39f,
                            Title = "Film C"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Director = "Person D",
                            Price = 15.41f,
                            Title = "Film D"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Director = "Person D",
                            Price = 12.25f,
                            Title = "Film E"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Director = "Person D",
                            Price = 1.79f,
                            Title = "Film F"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Director = "Person A",
                            Price = 37.43f,
                            Title = "Film G"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Director = "Person B",
                            Price = 57.46f,
                            Title = "Film H"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Director = "Person C",
                            Price = 27.29f,
                            Title = "Film I"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Director = "Person B",
                            Price = 19.99f,
                            Title = "Film J"
                        });
                });

            modelBuilder.Entity("UkwWypozyczalnia.Models.Film", b =>
                {
                    b.HasOne("UkwWypozyczalnia.Models.Category", "Category")
                        .WithMany("Films")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("UkwWypozyczalnia.Models.Category", b =>
                {
                    b.Navigation("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
